// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="advios,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.330000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=151,HLS_SYN_LUT=200}" *)

module advios (
        clk,
        reset,
        inSwitch,
        ctrl,
        outLeds
);


input   clk;
input   reset;
input  [3:0] inSwitch;
input  [3:0] ctrl;
output  [3:0] outLeds;

reg[3:0] outLeds;

wire   [0:0] advios_ssdm_threa_load_fu_128_p1;
wire   [1:0] ap_CS_fsm;
wire   [27:0] grp_advios_countThread_fu_80_advios_count_V;
wire    grp_advios_countThread_fu_80_advios_count_V_ap_vld;
wire    grp_advios_countThread_fu_80_sec_pulse;
wire    grp_advios_countThread_fu_80_sec_pulse_ap_vld;
wire   [3:0] grp_advios_iosThread_fu_104_outLeds;
wire    grp_advios_iosThread_fu_104_outLeds_ap_vld;
wire   [3:0] grp_advios_iosThread_fu_104_advios_switchs_V;
wire    grp_advios_iosThread_fu_104_advios_switchs_V_ap_vld;
wire   [3:0] grp_advios_iosThread_fu_104_advios_control_V;
wire    grp_advios_iosThread_fu_104_advios_control_V_ap_vld;
wire   [3:0] grp_advios_iosThread_fu_104_advios_sec_counter_V;
wire    grp_advios_iosThread_fu_104_advios_sec_counter_V_ap_vld;
wire    grp_advios_iosThread_fu_104_sec_pulse;
wire    ap_CS_fsm_state2;
reg   [0:0] sec_pulse;

advios_countThread grp_advios_countThread_fu_80(
    .ap_clk(clk),
    .ap_rst(reset),
    .advios_count_V(grp_advios_countThread_fu_80_advios_count_V),
    .advios_count_V_ap_vld(grp_advios_countThread_fu_80_advios_count_V_ap_vld),
    .sec_pulse(grp_advios_countThread_fu_80_sec_pulse),
    .sec_pulse_ap_vld(grp_advios_countThread_fu_80_sec_pulse_ap_vld)
);

advios_iosThread grp_advios_iosThread_fu_104(
    .ap_clk(clk),
    .ap_rst(reset),
    .inSwitch(inSwitch),
    .ctrl(ctrl),
    .outLeds(grp_advios_iosThread_fu_104_outLeds),
    .outLeds_ap_vld(grp_advios_iosThread_fu_104_outLeds_ap_vld),
    .advios_switchs_V(grp_advios_iosThread_fu_104_advios_switchs_V),
    .advios_switchs_V_ap_vld(grp_advios_iosThread_fu_104_advios_switchs_V_ap_vld),
    .advios_control_V(grp_advios_iosThread_fu_104_advios_control_V),
    .advios_control_V_ap_vld(grp_advios_iosThread_fu_104_advios_control_V_ap_vld),
    .advios_sec_counter_V(grp_advios_iosThread_fu_104_advios_sec_counter_V),
    .advios_sec_counter_V_ap_vld(grp_advios_iosThread_fu_104_advios_sec_counter_V_ap_vld),
    .sec_pulse(grp_advios_iosThread_fu_104_sec_pulse)
);

always @ (posedge clk) begin
    if ((1'b1 == grp_advios_iosThread_fu_104_outLeds_ap_vld)) begin
        outLeds <= grp_advios_iosThread_fu_104_outLeds;
    end
end

always @ (posedge clk) begin
    if ((1'b1 == grp_advios_countThread_fu_80_sec_pulse_ap_vld)) begin
        sec_pulse <= grp_advios_countThread_fu_80_sec_pulse;
    end
end

assign advios_ssdm_threa_load_fu_128_p1 = 1'd0;

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_advios_iosThread_fu_104_sec_pulse = sec_pulse;

endmodule //advios
