// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xadvios.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAdvios_CfgInitialize(XAdvios *InstancePtr, XAdvios_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAdvios_SetCtrl(XAdvios *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAdvios_WriteReg(InstancePtr->Slv0_BaseAddress, XADVIOS_SLV0_ADDR_CTRL_DATA, Data);
}

u32 XAdvios_GetCtrl(XAdvios *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAdvios_ReadReg(InstancePtr->Slv0_BaseAddress, XADVIOS_SLV0_ADDR_CTRL_DATA);
    return Data;
}

